export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const MENU_IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/";

// export const FETCH_MENU_URL =
//   "https://www.swiggy.com/dapi/menu/v4/full?lat=19.45953&lng=72.817498&menuId=";

export const FETCH_MENU_URL = (id) => {
  return `https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=19.4559185&lng=72.7762815&restaurantId=${id}&submitAction=ENTER`;
};

export const AWS_POST_DATA_URL =
  "https://2nwc1shv5j.execute-api.ap-south-1.amazonaws.com/default/clickstreamdata";
export const AWS_GET_DATA_URL =
  "https://2nwc1shv5j.execute-api.ap-south-1.amazonaws.com/default/clickstreamdata?userId=";

export const restaurantList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "609479",
      name: "The Bengal Sweets",
      uuid: "9d633805-93eb-4823-a0ea-9a213db418bc",
      city: "5",
      area: "Virar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "awisxsiivfqu3as8wub2",
      cuisines: ["Desserts", "Snacks"],
      tags: [],
      costForTwo: 5000,
      costForTwoString: "₹50 FOR TWO",
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: "22 MINS",
      lastMileTravel: 2.5999999046325684,
      slugs: {
        restaurant: "the-bengal-sweets-virar-virar",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "Shop No 37, Agarwal Paramount, Rustomjee Global City, Virar West, Virar, Maharashtra 401303, India",
      locality: "Virar West",
      parentId: 362304,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "609479",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 2.5999999046325684,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    scrubber: {
      value: "₹50 FOR TWO",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "617830",
      name: "Master Chef Vasaikar",
      uuid: "983d4850-7fff-4d76-bc9e-87c79a596a7a",
      city: "5",
      area: "Vasai",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "jm2ow2ofnptftasdyupf",
      cuisines: ["Indian", "Fast Food", "Snacks"],
      tags: [],
      costForTwo: 8000,
      costForTwoString: "₹80 FOR TWO",
      deliveryTime: 50,
      minDeliveryTime: 50,
      maxDeliveryTime: 50,
      slaString: "50 MINS",
      lastMileTravel: 7.400000095367432,
      slugs: {
        restaurant: "master-chef-vasaikar-vasai-vasai",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "WING-141/301, TAURUS HOUSING SOCIETY, 143, Jawaharlal Nehru Rd, ????????? ????, ??? ?????, ???, ?????????? 401209, India",
      locality: "Jawaharlal Nehru Road",
      parentId: 368218,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 7500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 7500,
        message: "",
        title: "Delivery Charge",
        amount: "7500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7.4 kms",
      hasSurge: false,
      sla: {
        restaurantId: "617830",
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        lastMileTravel: 7.400000095367432,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    scrubber: {
      value: "₹80 FOR TWO",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "617809",
      name: "jhakkas vada pav katta",
      uuid: "113a9f8b-1b0c-4dd7-bd06-b054179991c0",
      city: "5",
      area: "Virar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "zeu8yracct9r1m2csgq3",
      cuisines: ["Snacks", "Beverages"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: "22 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant: "jhakkas-vada-pav-katta-virar-virar",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "shop no 3, building name kamala center tiwari, block sector: virar east 401305,Road Narangi road,opp Parekh industrial, Virar (E) District: Palghar, Vasai Tahashil, Palghar Zone 2, Maharashtra - 40130",
      locality: "Road Narangi Road",
      parentId: 369401,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfo: {
        header: "10% off",
        shortDescriptionList: [
          {
            meta: "10% off | Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "10% off up to ₹40 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      aggregatedDiscountInfoV2: {
        header: "10% OFF",
        shortDescriptionList: [
          {
            meta: "Use TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        descriptionList: [
          {
            meta: "10% off up to ₹40 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },
        ],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      sla: {
        restaurantId: "617809",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    scrubber: {
      value: "₹100 FOR TWO",
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "526156",
      name: "The Jerry likes",
      uuid: "16687c43-a6fa-4b38-b998-c3bd2e1b33af",
      city: "5",
      area: "Virar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "pyscvhptfx2spwf3nviv",
      cuisines: ["Bakery", "Desserts", "Beverages"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: "22 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "the-jerry-likes-virar-virar",
        city: "mumbai",
      },
      cityState: "5",
      address:
        "Veer Savarkar Marg, Sai Datt Nagar, Virar East, Virar, Maharashtra 401305, India",
      locality: "Virar East",
      parentId: 210189,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3500,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3500,
        message: "",
        title: "Delivery Charge",
        amount: "3500",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "526156",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    scrubber: {
      value: "₹100 FOR TWO",
    },
  },
];
